In [1]:
import sklearn

In [2]:
print(sklearn.__version__)

1.0.2


In [ ]:
class CEstimator():
    def fit():
        pass
    def predict():
        pass

class Classifier(Estimator):
    pass

In [19]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
import pandas as pd

In [8]:
iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [9]:
iris_data = iris.data
iris_target = iris.target

In [30]:
X_train, X_test, y_train, y_test = train_test_split(iris_data,
                                                   iris_target,
                                                   stratify=iris_target,
                                                    test_size=0.3,
                                                   random_state=2022)

In [31]:
dtc = DecisionTreeClassifier(random_state=2022).fit(X_train, y_train)
dtc.score(X_test, y_test)

0.9555555555555556

In [32]:
dtc.classes_

array([0, 1, 2])

In [37]:
pred = dtc.predict(X_test)
print('정확도 :', accuracy_score(y_test, pred))
print('f1_score :', f"{f1_score(y_test, pred, average='weighted'):.4f}")

정확도 : 0.9555555555555556
f1_score : 0.9554


In [46]:
from sklearn.model_selection import KFold
kf = KFold()
kf.get_n_splits(X_train)

In [45]:
for train_index, test_index in kf.split(X_train):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100 101 102 103 104] TEST: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
TRAIN: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100 101 102 103 104] TEST: [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]
TRAIN: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  3

In [53]:
kfold = KFold(n_splits=5)
features = iris.data
labels = iris.target
dt_clf = DecisionTreeClassifier(random_state=2022)
cv_accuracy = []

In [55]:
import numpy as np
n_iter = 0
for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = labels[train_index], labels[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred= dt_clf.predict(X_test)
    n_iter += 1
    
    accuracy = round(accuracy_score(y_test, pred), 4)
    train_size=  X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n\{0} 교차검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(
    n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인텍스 : {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
print('\n## 평균 검증 정확도 : ', np.mean(cv_accuracy))


\1 교차검증 정확도 : 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#1 검증 세트 인텍스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

\2 교차검증 정확도 : 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#2 검증 세트 인텍스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

\3 교차검증 정확도 : 0.8333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#3 검증 세트 인텍스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

\4 교차검증 정확도 : 0.9333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#4 검증 세트 인텍스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

\5 교차검증 정확도 : 0.8, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#5 검증 세트 인텍스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도 :  0.9133200000000002


In [59]:
next(kfold.split(features))

(array([ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
         69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
         82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
         95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
        108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
        134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
        147, 148, 149]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))

In [60]:
type(kfold.split(features))

generator

In [61]:
import pandas as pd
iris = load_iris()

iris_df = pd.DataFrame(iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [64]:
fold = KFold(n_splits=3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차검증 : {0}'.format(n_iter))
    print('학습 레이블 데이터 분포 : \n', label_train.value_counts())
    print('검증 레이블 데이터 분포 : \n', label_test.value_counts())

## 교차검증 : 1
학습 레이블 데이터 분포 : 
 1    50
2    50
0    20
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
 0    30
Name: label, dtype: int64
## 교차검증 : 2
학습 레이블 데이터 분포 : 
 2    50
1    40
0    30
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
 0    20
1    10
Name: label, dtype: int64
## 교차검증 : 3
학습 레이블 데이터 분포 : 
 0    50
2    50
1    20
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
 1    30
Name: label, dtype: int64
## 교차검증 : 4
학습 레이블 데이터 분포 : 
 0    50
1    40
2    30
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
 2    20
1    10
Name: label, dtype: int64
## 교차검증 : 5
학습 레이블 데이터 분포 : 
 0    50
1    50
2    20
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
 2    30
Name: label, dtype: int64


In [66]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits = 3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df.label) :
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차검증 : {0}'.format(n_iter))
    print('학습 레이블 데이터 분포 : \n', label_train.value_counts())
    print('검증 레이블 데이터 분포 : \n', label_test.value_counts())

## 교차검증 : 1
학습 레이블 데이터 분포 : 
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차검증 : 2
학습 레이블 데이터 분포 : 
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차검증 : 3
학습 레이블 데이터 분포 : 
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
 1    17
2    17
0    16
Name: label, dtype: int64


In [113]:
skf = StratifiedKFold(n_splits = 3, shuffle=True)
cv_accuracy = []
dt_clf = DecisionTreeClassifier(random_state=2022)
n_iter = 0
for train_index, test_index in skf.split(iris_df, iris_df.label):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = labels[train_index], labels[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred= dt_clf.predict(X_test)
    n_iter += 1
    
    accuracy = round(accuracy_score(y_test, pred), 4)
    train_size=  X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n\{0} 교차검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(
    n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인텍스 : {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    print('\n## 교차 검증별 정확도 : ', np.round(accuracy, 4))
print('\n## 교차 검증별 정확도: ', np.round(cv_accuracy, 4))
print('\n## 평균 검증 정확도 : ', np.mean(cv_accuracy))


\1 교차검증 정확도 : 0.96, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#1 검증 세트 인텍스 : [  0   2   5  10  17  18  19  20  24  25  26  30  31  32  43  48  49  55
  60  62  63  67  68  69  74  75  77  81  82  83  85  87  88  90 100 103
 106 107 109 112 116 117 121 122 124 130 134 135 136 144]

## 교차 검증별 정확도 :  0.96

\2 교차검증 정확도 : 0.94, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#2 검증 세트 인텍스 : [  3   7  11  14  21  23  33  34  35  36  37  38  40  41  42  44  46  54
  56  61  64  65  66  70  72  76  78  79  80  84  91  93  97 102 108 110
 114 115 119 120 123 127 128 133 137 138 139 140 142 145]

## 교차 검증별 정확도 :  0.94

\3 교차검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#3 검증 세트 인텍스 : [  1   4   6   8   9  12  13  15  16  22  27  28  29  39  45  47  50  51
  52  53  57  58  59  71  73  86  89  92  94  95  96  98  99 101 104 105
 111 113 118 125 126 129 131 132 141 143 146 147 148 149]

## 교차 검증별 정확도 :  0.98

## 교차 검증별 정확도:  [0.96 0.94 0.98]

## 평균 검증 정확도 :  0.96


In [120]:
from sklearn.model_selection import cross_val_score, cross_validate

In [125]:
dt_clf = DecisionTreeClassifier(random_state=156)
data = iris.data
label = iris.target
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
scores

array([0.98, 0.94, 0.98])

In [126]:
from sklearn.model_selection import GridSearchCV

In [132]:
dtree = DecisionTreeClassifier()

parameters = {'max_depth' : [1, 2, 3],
             'min_samples_split' : [2,3]}
grid_dtree = GridSearchCV(dtree, param_grid = parameters, cv=3, refit=True)
grid_dtree.fit(X_train, y_train)
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score',
         'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.669935                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.669935                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.939691                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.939691                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.949792                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.949792                1   

   split0_test_score  split1_test_score  split2_test_score  
0           0.676471           0.666667           0.666667  
1           0.676471           0.666667           0.666667  
2           0.970588           0.909091           0.939394  
3           0.970588           0.909091           0.939394  
4           0.970588           0.909091           0.969697  
5           0.970588           0.909091           0.969697

In [139]:
grid_dtree.best_estimator_.score(X_test, y_test)

0.98

In [138]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [144]:
from sklearn.preprocessing import LabelEncoder
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 : ', labels)

print(encoder.classes_)
print(encoder.inverse_transform([0, 1, 4, 5, 3, 3, 2, 2]))

인코딩 변환값 :  [0 1 4 5 3 3 2 2]
['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


In [150]:
from sklearn.preprocessing import OneHotEncoder
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

labels = labels.reshape(-1, 1)
oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)
print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


In [152]:
df = pd.DataFrame({'item' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        1         0           0         0
6        0         0        1         0           0         0

In [153]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [157]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

iris_scaled = scaler.fit_transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [158]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

iris_scaled = scaler.fit_transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.052908
sepal width (cm)     0.032983
petal length (cm)    0.089522
petal width (cm)     0.100869
dtype: float64


# 타이타닉

In [161]:
!pwd

/c/Users/Admin/2022fin/癒몄떊�윭�떇_�뵦�윭�떇


In [163]:
df = pd.read_csv('./data/titanic_train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [165]:
df.shape

(891, 12)

In [169]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [167]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200