## 넘파이?

Numerical Python - 행열 연산이나 다차원 배열을 편리하게 처리  
배열(array) 단위로 백터, 행열 연상등을 파이썬의 기본 리스트에 비해 빠르고 적은양의 메모리로 연산  
브로드캐스트 지원 - 형태(차원)가 다른 행렬끼리의 계산

https://numpy.org/

In [1]:
import numpy as np

## 사용하는 이유?

In [2]:
matrix_1 = [[1, 2],[3, 4]]
matrix_2 = [[5, 6],[7, 8]]
matrix_result = []

#행렬합 (파이썬 리스트사용)
for i in range(len(matrix_1)):
    tmp = []
    for j in range(len(matrix_2)):
        tmp.append(matrix_1[i][j]+matrix_2[i][j])
    matrix_result.append(tmp)
    
print(matrix_result)


#행렬합 (넘파이)
matrix_result = np.array(matrix_1) + np.array(matrix_2)
print(matrix_result)

[[6, 8], [10, 12]]
[[ 6  8]
 [10 12]]


In [3]:
#숫자와의 연산 (파이썬 리스트사용)

matrix_1 = [[1, 2],[3, 4]]

for i in range(len(matrix_1)):
    for j in range(len(matrix_2)):
        matrix_1[i][j] = matrix_1[i][j] + 1
        
print(matrix_1)

[[2, 3], [4, 5]]


In [4]:
#숫자와의 연산 (넘파이)

matrix_1 = [[1, 2],[3, 4]]

np.array(matrix_1) + 1

array([[2, 3],
       [4, 5]])

In [5]:
matrix_1 = [['aa', 'bb'],[3.4, 1]]

np.array(matrix_1)

array([['aa', 'bb'],
       ['3.4', '1']], dtype='<U32')

## 속도비교

In [6]:
import time

size = 10000000

#list
x = list(range(size))
y = list(range(size))

start_time = time.time()
z = [x[i]+x[i] for i in range(size)]
print("리스트 걸린시간", time.time()-start_time)

#adlist (넘파이)
x = np.arange(size)
y = np.arange(size)
start_time = time.time()
z = x + y
print("넘파이 걸린시간", time.time()-start_time)

리스트 걸린시간 1.7261569499969482
넘파이 걸린시간 0.13909697532653809


## ndarray

In [7]:
x = np.uint(32)
print(x)
print(x.dtype)

32
uint32


In [8]:
x = np.array([1, 2, 3, 4])
print(x)
print(x.dtype)

[1 2 3 4]
int32


In [9]:
x = np.float32([1, 2, 3, 4])
print(x)
print(x.dtype)

[1. 2. 3. 4.]
float32


In [10]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
print(x)
print(x.dtype)

x = np.int32(x)
print(x)
print(x.dtype)
np.issubdtype(x.dtype, np.int32)

[1. 2. 3. 4.]
float32
[1 2 3 4]
int32


True

## 다차원 ndarray

In [11]:
x = np.array(1)
print(x.shape)
print(x.ndim)
print(x.size)

()
0
1


In [12]:
x = np.array([1, 2])
print(x.shape)
print(x.ndim)
print(x.size)

(2,)
1
2


In [13]:
x = np.array([[1, 2, 3],[4, 5, 6]])
print(x.shape)
print(x.ndim)
print(x.ndim)

(2, 3)
2
2


## arange

In [14]:
x = np.arange(10)
print(x)
x = np.arange(10.0)
print(x)
x = np.arange(1, 10, 2)
print(x)
x = np.arange(1, 10, 0.5)
print(x)
x = np.arange(10, 1, -0.5)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1 3 5 7 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


## linspace

In [15]:
x = np.linspace(1, 20, 5)
print(x)

[ 1.    5.75 10.5  15.25 20.  ]


In [16]:
x = np.linspace(1, 20, 10, endpoint=False)
print(x)

[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1]


## reshape

In [17]:
x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
x = np.arange(24).reshape(2, 3, 4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [19]:
x = np.arange(16).reshape(2, 2, 2, 2)
print(x)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [20]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)
print(x.reshape(2,3))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [21]:
x = np.arange(9).reshape(3, -1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## slicing

In [22]:
x = np.arange(20)
print(x[1:3])

[1 2]


In [23]:
x = np.arange(20).reshape(4,5)
print(x)
print(x[1:3])
print(x[1:3, 1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 6  7]
 [11 12]]


In [24]:
x = np.arange(30).reshape(2,5,3)
print(x)
print(x[:,3:5,1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[10 13]
 [25 28]]


## indexing & boolean indexing

In [25]:
a = np.arange(20).reshape(4, 5)
print(a)

print(a[1][1])
print(a[1,1])
print(a[[1,1],[1,2]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
6
6
[6 7]


In [26]:
a = np.arange(20).reshape(4, 5)
print(a)

print(a > 3)
print(a[a > 3])
print(a[a == 1])
print(a[~(a == 1)])
print(a[(a > 3)&(a < 8)])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1]
[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[4 5 6 7]


## random

In [27]:
np.random.rand(5,5)

array([[0.06573065, 0.51568925, 0.84165071, 0.52539004, 0.13207606],
       [0.26404871, 0.13980609, 0.50930458, 0.02661379, 0.60855763],
       [0.32689261, 0.52797352, 0.77679947, 0.73032405, 0.44527838],
       [0.83882244, 0.49658233, 0.80745575, 0.60788656, 0.98028606],
       [0.17462269, 0.7830518 , 0.44026395, 0.57312644, 0.92786437]])

In [14]:
np.random.randint(1, 2)

1

In [29]:
np.random.randint(1, 10, size=(5))

array([9, 8, 7, 7, 1])

In [30]:
np.random.randint(1, 10, size=(5, 5))

array([[8, 7, 1, 1, 7],
       [1, 5, 8, 7, 6],
       [6, 4, 4, 4, 9],
       [9, 3, 2, 6, 6],
       [5, 9, 4, 9, 5]])

## 특별한 형태의 배열

In [31]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
x = np.random.randint(1, 10, size=(5, 5))
y = np.eye(5)
print(x)
z = np.dot(x, y)
print(z)

[[8 6 8 2 4]
 [9 2 6 2 7]
 [6 7 8 5 3]
 [8 4 1 7 7]
 [6 6 9 7 7]]
[[8. 6. 8. 2. 4.]
 [9. 2. 6. 2. 7.]
 [6. 7. 8. 5. 3.]
 [8. 4. 1. 7. 7.]
 [6. 6. 9. 7. 7.]]


In [35]:
x = np.random.randint(1, 10, size=(5, 5))
print(x)
print(x.ravel())
print(x.ravel(order='F'))

[[7 3 7 3 6]
 [7 1 9 8 3]
 [6 4 4 2 7]
 [7 4 5 9 2]
 [1 9 4 8 8]]
[7 3 7 3 6 7 1 9 8 3 6 4 4 2 7 7 4 5 9 2 1 9 4 8 8]
[7 7 6 7 1 3 1 4 4 9 7 9 4 5 4 3 8 2 9 8 6 3 7 2 8]


## concatenate

In [36]:
x = np.arange(1, 4)
y = np.arange(4, 7)

np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [37]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)

np.concatenate([x, y])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

## split

In [39]:
x = np.arange(12)
print(x)
np.split(x, 4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [40]:
x = np.arange(16).reshape(4, 4)
print(x)
np.split(x, 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [41]:
x = np.arange(16).reshape(4, 4)
print(x)
np.split(x, 2, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## broadcast

In [42]:
x = np.array([1,2,3])
x + 1

array([2, 3, 4])

In [43]:
x = np.arange(1, 10).reshape(3, 3)
y = np.arange(1, 4)
x + y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [44]:
x = np.array([10, 20, 30]).reshape(3, 1)
y = np.arange(1, 4)
x + y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

## 연산 및 집계함수

In [45]:
x = np.arange(3, 7).reshape(2, 2)
y = np.arange(4).reshape(2, 2)
x.dot(y) #행렬곱

array([[ 8, 15],
       [12, 23]])

In [46]:
np.transpose(x) #전치행렬

array([[3, 5],
       [4, 6]])

In [47]:
np.linalg.inv(x) #역행렬

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [48]:
np.linalg.det(x) #행렬식

-1.9999999999999971

In [49]:
np.median(x) #중간값

4.5

In [50]:
np.std(x) #표준편차

1.118033988749895

In [51]:
np.var(x) #분산

1.25

In [52]:
np.sum(x) #합

18

In [53]:
np.sum(x, axis=1) #합, 축변경

array([ 7, 11])

In [54]:
np.cumsum(x) #누적합

array([ 3,  7, 12, 18])

In [55]:
np.argmin(x) #최소값 위치

0

In [56]:
np.argmax(x) #최대값 위치

3

In [57]:
np.any(x) #하나라도 참이어야 참

True

In [58]:
np.all(x) #모든요소가 참이어야 참

True

In [59]:
np.all(x > 4)

False

In [60]:
np.where(x > 4)

(array([1, 1], dtype=int64), array([0, 1], dtype=int64))

In [ ]:
np.where(x > 4, x, -100)

## 실습1

In [2]:
x=[1, 2, 3, 4, 5, 6, 7, 8, 9]
y=[10, 20, 30, 40, 50, 60, 70, 80, 90]
x = np.array(x).reshape(3,3)
y = np.array(y).reshape(3,3)
print(x+y)
result = np.dot(x,y)
result

[[11 22 33]
 [44 55 66]
 [77 88 99]]


array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

## 실습2

In [66]:
ar1 = np.linspace(1, 20, 30)
ar1 += 10
ar1

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

## 실습3

In [80]:
ar1 = np.random.randint(1, 101, size=(2,10,10))
print(ar1)
ar_result = np.where(ar1 >= 50, 1, 2)
print(ar_result)
ar_result[1, 5:, 5:]

[[[36 55 50  6 73 20 17 67 53 92]
  [86 74 39 10 32 79 67 73 43 28]
  [68 88 97 92 85 41 38 20 99 99]
  [70 93 91 94 33 78 83 76 30 53]
  [29 26 97 84 20 69 57 37 44 60]
  [32 64 53 93 14 75 67 94 66 41]
  [96 28 48 52  8 72 73  7 73 44]
  [78 20 58  4 54 73 53 45 49 13]
  [78 45 25 80 57 77 72 42 63 42]
  [54 67 44 69 39 74 58 14 47 84]]

 [[79 89 97 65  6 22 51 55 46  6]
  [61  3  3 87 24 45 35 81 25 69]
  [66 44 71 57 55 68 95 17 70 66]
  [ 4 72 56 13 13 90  1 31 92  8]
  [ 5 16  1 87 18 81 95 45 97 22]
  [45 81 60 57  7 96 69 74 70 85]
  [63 79 12 28 63 52 49 27 15 97]
  [91 13 71 24 61 70 48 77 43 36]
  [ 5 17 94 38 55 21 50 27 30 59]
  [92 82  8 33 35 21 86 51  1 71]]]
[[[2 1 1 2 1 2 2 1 1 1]
  [1 1 2 2 2 1 1 1 2 2]
  [1 1 1 1 1 2 2 2 1 1]
  [1 1 1 1 2 1 1 1 2 1]
  [2 2 1 1 2 1 1 2 2 1]
  [2 1 1 1 2 1 1 1 1 2]
  [1 2 2 1 2 1 1 2 1 2]
  [1 2 1 2 1 1 1 2 2 2]
  [1 2 2 1 1 1 1 2 1 2]
  [1 1 2 1 2 1 1 2 2 1]]

 [[1 1 1 1 2 2 1 1 2 2]
  [1 2 2 1 2 2 2 1 2 1]
  [1 2 1 1 1 1 1 2 1 1]
  

array([[1, 1, 1, 1, 1],
       [1, 2, 2, 2, 1],
       [1, 2, 1, 2, 2],
       [2, 1, 2, 2, 1],
       [2, 1, 1, 2, 1]])