In [6]:
# 행렬 합 구하기
matrix_1 = [
    [1, 2],
    [3, 4]
]

matrix_2 = [
    [5, 6],
    [7, 8]
]

# 예상된 결과
result = [
    [6, 8],
    [10, 12]
]

In [7]:
row = 0
column = 1
matrix_1[row][column]

2

In [8]:
result = [
    [0, 0],
    [0, 0]
]

In [9]:
for row in range(2):
    for column in range(2):
        result[row][column] = matrix_1[row][column] + matrix_2[row][column] 
result

[[6, 8], [10, 12]]

In [11]:
import numpy as np
result = np.array(matrix_1) + np.array(matrix_2)
result

array([[ 6,  8],
       [10, 12]])

In [14]:
x = np.uint(40)
print(x.dtype)

uint32


In [15]:
x = np.array([1, 2, 3, 4])
x.dtype

dtype('int32')

In [16]:
x = np.float32([ 1, 2, 3, 4])
x.dtype

dtype('float32')

In [17]:
x = np.linspace(1, 20, 5)
x

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [19]:
x = np.linspace(1, 20, 5, endpoint=True)
x

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [20]:
x = np.arange(30).reshape(2, 5, 3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [24]:
x=[1, 2, 3, 4, 5, 6, 7, 8, 9]
y=[10, 20, 30, 40, 50, 60, 70, 80, 90]
x = np.array(x).reshape(3,3)
y = np.array(y).reshape(3,3)

x + y , np.dot(x,y)

(array([[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]]),
 array([[ 300,  360,  420],
        [ 660,  810,  960],
        [1020, 1260, 1500]]))